#! /bin/bash
set -e

#APPDIR=`pwd`

LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${APPDIR}/lib"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}

QT_PLUGIN_PATH="${QT_PLUGIN_PATH}:${APPDIR}/lib/qt5/plugins:${APPDIR}/lib/qt5/plugins/platforms"
export QT_PLUGIN_PATH=${QT_PLUGIN_PATH}

cd ${HOME}

${APPDIR}/application/flareget $@
